version: '3.5'

services:
  db:
    image: mariadb:10.6.2
    restart: always
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
